<?php $_esthelper = $this->helper('KDC\HidePrice\Helper\Data'); ?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <fieldset class="fieldset">
         <?php if ($block->shouldRenderQuantity()): ?>
             <div class="field qty">
                <label class="label" for="qty"><span><?php echo __('Qty') ?></span></label>
                <div class="control">
                    <input type="number"
                           name="qty"
                           id="qty"
                           maxlength="12"
                           value="<?php echo $block->getProductDefaultQty() * 1 ?>"
                           title="<?php echo __('Qty') ?>" class="input-text qty"
                           data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                           />
                </div>
            </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </fieldset>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>

<!-- Start code to hide price -->
<?php if(!$_esthelper->isCustomerlogin() && $_esthelper->isenable()): ?>
    <!-- Display button if text is not blank -->
	<?php if($_esthelper->getbuttontext() != '' && !$_esthelper->isCustomerlogin() && $_esthelper->isenable()): ?>
		<?php  $loginbutton='<a  class="action tocart primary" href="'.$block->getUrl('customer/account/login').'">'.$_esthelper->getbuttontext().'</a>';?>
		        <script type="text/javascript">
            require([
                'jquery',
                'domReady!'
            ], function($) {
                'use strict';

                jQuery('.price-box').html('<?php  echo $_esthelper->estmessage();?>');
                jQuery('.box-tocart .actions').html('<?php  echo $loginbutton;?>');
                if(jQuery('.prices-tier').length>0) {
                    jQuery('.prices-tier').remove();
                }

                <!--jQuery('.product-addto-links .towishlist').remove();-->
            });

        </script>	
	<!-- If button is empty, don't show it. -->
	<?php elseif($_esthelper->getbuttontext() == '' && !$_esthelper->isCustomerlogin() && $_esthelper->isenable()): ?>
		        <script type="text/javascript">
            require([
                'jquery',
                'domReady!'
            ], function($) {
                'use strict';

                jQuery('.price-box').html('<?php  echo $_esthelper->estmessage();?>');
                //jQuery('.box-tocart .actions').html('');
				jQuery('.box-tocart .qty').html('');
                if(jQuery('.prices-tier').length>0) {
                    jQuery('.prices-tier').remove();
                }

                <!--jQuery('.product-addto-links .towishlist').remove();-->
            });

        </script>	
	<?php endif; ?>
<?php endif; ?>
<!-- Start code to hide price -->
  